### ISSUE TITLE
Cannot setup automatically value to PostalCode and as I think to other elements as well

### ISSUE THREAD

**Issue by Gemofort** [ectoflow/vue-stripe-elements#101]
Have a problem with setting up a value to inputs seems like in the docs that is possible and even looking at 
<img width="287" alt="Screenshot 2020-02-12 at 15 04 02" src="https://user-images.githubusercontent.com/36796340/74337412-e9c3f700-4da8-11ea-9a01-2e4cf4dac21c.png">
gives me some hope to it :) 
So I was wondering if this could work and came to the conclusion that not, maybe I am doing something wrong, so would be glad for any help.
<img width="339" alt="Screenshot 2020-02-12 at 15 06 41" src="https://user-images.githubusercontent.com/36796340/74337612-48897080-4da9-11ea-8b67-f8d0a1485d1c.png">
I replaced stripe key just for the screenshot. 
<img width="616" alt="Screenshot 2020-02-12 at 15 07 37" src="https://user-images.githubusercontent.com/36796340/74337675-69ea5c80-4da9-11ea-9652-b1a69cd8754a.png">
As you can see nothing changed at all, so let's look at vue dev tools.
<img width="572" alt="Screenshot 2020-02-12 at 15 08 59" src="https://user-images.githubusercontent.com/36796340/74337774-a027dc00-4da9-11ea-9437-cd6c130b55c0.png">
As you can see value is set up but isn't shown in the way it must be in my opinion

**Comment by inspire22** [comment]
DId you ever get this working?

Also, unrelated but what inspector are you using at the bottom screenshot?

**Comment by Gemofort** [comment]
@inspire22 Unfortunately not, I tried going deep into the library and seemed like they didn't finish that part of it. So yeah, anyway, I just left it as it was since the start. The inspector, you are talking about, is Vue extension in Google Chrome which is very useful.

**Comment by softbeehive** [comment]
Hey, element options are reactive since `v1.0.0`
https://github.com/ectoflow/vue-stripe-elements#options
