### ISSUE TITLE
Remove lodash dependency if not used

### ISSUE THREAD

**Issue by siegerts** [ectoflow/vue-stripe-elements#104]
Looks like there is a single dependency of `lodash`.  It would be great to drop that or only leverage the specific module that's used.  I looked through the lib but did not see any references...

Thanks!

**Comment by sjelfull** [comment]
You can also use `lodash-es` to enable treeshaking if you want to use `lodash` at all.

**Comment by softbeehive** [comment]
Fair enough, it's not even used. Will remove, thanks for reporting!

**Comment by softbeehive** [comment]
Fixed by #120
