### ISSUE TITLE
Can't set StripeAccount to an instance

### ISSUE THREAD

**Issue by perle-rare** [ectoflow/vue-stripe-elements#106]
Hi, 
I'm using this pluging to manage my stripe payment, but, I can't get-it work using a StripeAccount

Any help please ?? 

Thanks

**Comment by softbeehive** [comment]
Hi, I've just published v1.0.0, you can pass it with `instanceOptions`
```vue
<StripeElements
      :instance-options="instanceOptions"
      :stripe-key="stripeKey"
      ...
>
...
</StripeElements>
```

Check [examples](https://github.com/ectoflow/vue-stripe-elements#3-use-built-in-components)
