### ISSUE TITLE
StripeOptions not working correctly

### ISSUE THREAD

**Issue by jamols09** [ectoflow/vue-stripe-elements#113]
How do I make stripeOptions work correctly, the styles I've been is not working.

I have create a stripeConfig.json under my `src` folder.

stripeConfig.json
```
{
    "stripeKey": "pk_test_51HIFr56EvWK1GvmtnY4bfbRGhZfeI00aT73G4h1",
    "stripeOptions": {
        "base": {
            "iconColor": "#c4f0ff",
            "color": "#fff",
            "fontWeight": 500,
            "fontFamily": "Open Sans",
            "fontSize": "24px",
            "fontSmoothing": "antialiased"
        }
    }
  }
```
Ui looks broken in this screenshot
![image](https://user-images.githubusercontent.com/20100579/90954806-60555600-e4aa-11ea-9f19-d5ceb6ad9fa7.png)

inside my `data() return { ... }`
```
data() {
            return {
                loading: false,
                //Stripe Bill payment
                publishableKey: stripeKey,
                complete: false,
                stripeOptions: stripeOptions,
            }
```

Console Log

![image](https://user-images.githubusercontent.com/20100579/90954846-bb874880-e4aa-11ea-937d-b04f70b8585e.png)

**Comment by softbeehive** [comment]
I think you were missing **style** prop. https://stripe.com/docs/js/appendix/style
