### ISSUE TITLE
Vue3 is not supported

### ISSUE THREAD

**Issue by SteveLewisES** [ectoflow/vue-stripe-elements#118]
The Vue Stripe Components do not work with Vue3, the current version of Vue.

**Comment by softbeehive** [comment]
Hi, this is the top priority task. The package is a bit neglected, I took over and will invest some time in order to improve the design and maintainability.

**Comment by m3nu** [comment]
Thanks for taking over, @softbeehive. Nice to see some movement. Already updated my project to v1.0.1. 👍

**Comment by Lord-Y** [comment]
Can't wait for Vue 3 implementation.

**Comment by softbeehive** [comment]
Hey folks, little update on vue3 support. I've been busy with other stuff.

In the meantime backward-compatible version of vue3 has been released. I haven't checked if the current bundle works well with latest `vue/sfc-compiler`. Vue 3.0 was throwing SFC error messages.

My plan is to distribute vue3 compatible version as a separate package, I'll try to port it to typescript over the weekend

**Comment by jonnypage** [comment]
Any update on the Vue3 implementation?

**Comment by softbeehive** [comment]
Ported components to typescript. Preparing new package needs a bit of care. Short answer: Vue 3 compatible package coming this month

**Comment by softbeehive** [comment]
🥁🥁🥁 
Vue 3 compatible package has been released

```bash
npm i vue-stripe-js --save-dev
```

Docs:
https://github.com/ectoflow/vue-stripe-js

**Comment by softbeehive** [comment]
If you feel like you want to keep package healthy, consider donating, thanks!
