### ISSUE TITLE
"self is not defined" with Nuxt

### ISSUE THREAD

**Issue by lolbyaka** [ectoflow/vue-stripe-elements#126]
Hello.

I was using your library version 0.3.2 in a project with Nuxt.js and everything worked fine. But now I'm upgrading packages, and when I upgrade the `vue-stripe-elements` to the 1.0.1, I've got error `ReferenceError: self is not defined`. 

I've reproduced this behavior in sandbox - https://codesandbox.io/s/infallible-yalow-s7ph1?file=/pages/index.vue

**Comment by softbeehive** [comment]
Hi,
I've briefly checked it via your sandbox. I can see the issue and it may be related to umd build target https://github.com/ectoflow/vue-stripe-elements/blob/master/webpack.config.js#L12. Thanks for bringing this, I'll look for the cause.

**Comment by azmatzuberi** [comment]
I'm facing the same issue.

**Comment by azmatzuberi** [comment]
I'm using v1.0.1 of plus version

**Comment by softbeehive** [comment]
Fixed, please use v1.0.2. In case you wonder what caused it - https://github.com/webpack/webpack/issues/6784
