### ISSUE TITLE
[ Accessibility ] Auto Tab to Next Field Confuses Keyboard Users

### ISSUE THREAD

**Issue by heymynameisdina** [ectoflow/vue-stripe-elements#130]
Flagging a simple accessibility issue I've come across interacting with this tool. Looks like the inputs automatically send the user to the next input field when filled in. While I do find this to be a nice shortcut for the convenience of most users, automatic tabbing to the next field is confusing and unexpected for keyboard users/users with disabilities. Would suggest removing that if possible

**Comment by softbeehive** [comment]
Hi @heymynameisdina,

I saw auto-focus in advanced elements like `card`. It's handled by stripe-js, which is a library provided by stripe, and the dependency of this vue wrapper. I think I understand your concern. So I went and checked Stripe Documentation, but didn't find an option to disable the auto-focus.

I bound stripe-js event listeners and emit component instance events - [source code](https://github.com/ectoflow/vue-stripe-elements/blob/ec8204cea4c233e679341ac249b92f1f55b3f5e7/src/components/StripeElement.vue#L85)

Did you try?
```vue
<StripeElement 
  @focus.prevent="yourFocusHandler"
/>
```

More on events
https://stripe.com/docs/js/element/events/on_focus#element_on_focus-event
