### ISSUE TITLE
Payment Request Button feature (Apple & Android Pay, etc)

### ISSUE THREAD

**Issue by Chris1904** [ectoflow/vue-stripe-elements#19]
Hi,

just wondering if it is planned to include this for Pay with Google, Apple Pay, and the Payment Request API?

Would love to see this.

Best,
Chris

**Comment by softbeehive** [comment]
Hi Chris,

thank you for requesting the feature. We have been discussing Pay with Google and Apple Pay integration recently. I think it totally makes sense. I'd personally love to add Google and Apple Pay implementation examples to our readme. At the same time ideally vue-stripe-elements-plus module should be payment-method-agnostic.

But after reading through Stripe [documentation](https://stripe.com/docs/elements/payment-request-button) I think it requires some changes. I'll present my ideas on technical design of the feature here. Will keep you updated

**Comment by Chinese1904** [comment]
Awesome! Truly looking forward to this. And thanks for taking this into consideration!

**Comment by aldarund** [comment]
+1

**Comment by Chinese1904** [comment]
@softbeehive has there been any updates? Just wondering! 👍

**Comment by softbeehive** [comment]
Hope to add it in next major release `v1.0.0`

**Comment by Chinese1904** [comment]
Awesome! Any timeline for that?

**Comment by softbeehive** [comment]
**1.0.0** will be quite a big change. No timeline at this point but you'll be able to track the progress in repo's `Projects`.

**Comment by MatteoWebDesigner** [comment]
I could be interested to build this feature @softbeehive, we are using vue stripe on our product, if have time we could allocate some time to work on this.

**Comment by lorisleiva** [comment]
I've just had to create my own renderless component for that purpose and its only 65 lines of code. Here's the code:
https://gist.github.com/lorisleiva/69e537202d35d4ccd1b4a5cb8ddecf1c

It should be fairly simple to connect it with your StripeElement object. Hope this helps 🙂

**Comment by jcdodow** [comment]
Hey, i could not update the lib with the code of @lorisleiva .
Is there a solution planified to use the pay button ?

**Comment by emerg** [comment]
Hey, Just wanted to check on this as well, since this seems to be an old thread, but it's still marked as open. Is integrating with Apple Pay, through Stripe's paymentRequest button still something that's being worked on? I couldn't find anything in the docs for this package regarding that. I'm looking to be able to use Apple pay touch/face ID.

**Comment by sedrickcz** [comment]
Hey, 
yes, I added Apple Pay and Google Pay for v1.0.0 release.

**Comment by quiquelhappy** [comment]
Hello. Is this done? If so, how do I implement it? Thank you!

**Comment by ag-coder** [comment]
Hello all. Any news on the implementation state? Thanks

**Comment by fyllepo** [comment]
what is the latest one this please?

**Comment by softbeehive** [comment]
Hey folks, apologies for long wait and unfulfilled promise. I'm looking into it

**Comment by softbeehive** [comment]
`v1.0.0` is out
