### ISSUE TITLE
iframe buildup

### ISSUE THREAD

**Issue by dasDaniel** [ectoflow/vue-stripe-elements#34]
similar to https://github.com/stripe/react-stripe-elements/issues/99 the vue implementation allows iframes to build up.

in a SPA, using these components keeps injecting iframes to the dom. Is there a way to destroy them?

I'm using this for now in the wrapping component

```
  destroyed() {
    document.querySelectorAll('iframe').forEach(iframe => {
      if (iframe.getAttribute('src').includes('stripe')) {
        iframe.parentNode.removeChild(iframe);
      }
    });
  },
```

**Comment by softbeehive** [comment]
`vue-stripe-elements` is a vue wrapper for stripe js library. iframe creation is initiated by stripe library. This way stripe collects some telemetry, e.g. origin. I clearly see your point and I think iframe clean-up should be done by stripe library. For example when `element.destroy()` is called.

**Comment by softbeehive** [comment]
I'm gonna close it, clearly it's in stripe.js domain
