### ISSUE TITLE
Add more elements

### ISSUE THREAD

**Issue by SrPatinhas** [ectoflow/vue-stripe-elements#43]
Hello, It's possible to add more elements, like the name and more fields like in the [examples](https://stripe.github.io/elements-examples/).

**Comment by kushbhandari** [comment]
cardholder name will be a good addition!

**Comment by softbeehive** [comment]
Hi, in v1.0.0 all supported elements can be created using `StripeElement` component.
```html
<StripeElement type="iban" :elements="elements" />
```
