### ISSUE TITLE
How show card icon with single element

### ISSUE THREAD

**Issue by fabien44300** [ectoflow/vue-stripe-elements#59]
Hello,

When I use <card> ,I can see the Icon of the CardNumber (visa, master card,...)
But if I use each element <card-number><card-expiry><card-cvc>, there is no Icon of the CardNumber for the card-number element.

Is it possible to show it ?

Fabien

**Comment by RickKukiela** [comment]
I really need this for my app. Any idea when this will be added?

**Comment by MarceauKa** [comment]
Just add `showIcon: true` to CardNumber options

**Comment by softbeehive** [comment]
Closing, @MarceauKa answered the question
