### ISSUE TITLE
Invalid API Key provided, but this key works in non-Vue project

### ISSUE THREAD

**Issue by folmert** [ectoflow/vue-stripe-elements#65]
I've done everything as intructed in [Readme](https://www.npmjs.com/package/vue-stripe-elements-plus).

I'm using a stripe API key for test mode. When I fill in dummy credit card data and click pay

POST to https://api.stripe.com/v1/tokens

with data:
```
card[number]: 4242424242424242
card[cvc]: 222
card[exp_month]: 02
card[exp_year]: 22
card[address_zip]: 12345
guid: 162ec2ce-a4c1-4b5e-a0f1-5d875436dd79
muid: 43505269-2406-436f-acf2-52d1424beeac
sid: 506c0fac-4330-4116-9d23-4efd8055fc3d
payment_user_agent: stripe.js/061e956d; stripe-js-v3/061e956d
referrer: http://localhost:8000/dashboard/subscription-cost
key: (my key, censored)
```

returns 401 with response:
```
{
  "error": {
    "message": "Invalid API Key provided: pk_test_*******************kax7",
    "type": "invalid_request_error"
  }
}
```

The same key works when used in static html page implemented according to the stripe docs (by using `<script src="https://checkout.stripe.com/checkout.js">`).

**Comment by folmert** [comment]
Other thing I don't understand, why in the Readme you're instructing to inject **API in version 3** (`<script src="https://js.stripe.com/v3/"></script>)`, but this Vue plugin is making a call to **API version 1** (`https://api.stripe.com/v1/tokens`)?

**Comment by folmert** [comment]
That's interesting, token from https://stripe.com/docs/stripe-js/reference#element-options (tok_1Dz4ky2eZvKYlo2Cl0FyD424) works, so what can explain that our token doesn't?

**Comment by sithu-ab** [comment]
+1 I'm also encountering the same error
