### ISSUE TITLE
Not working on Safari on iOS. TypeError: undefined is not an object

### ISSUE THREAD

**Issue by techn0guy** [ectoflow/vue-stripe-elements#68]
Hello,
Recently customers on my site are reporting to me that they are unable to checkout. After digging deeper I found that some Safari browsers on iOS devices throw an error. I'm getting the error:
`TypeError: undefined is not an object (evaluating 'vm.$options')`

I'll post a snippet of my code:
All of my Stripe Elements have the following setup
`<card-expiry class='input stripe-element card-expiry'
                        id="stripe-card-expire"
                        ref='cardExpiry'
                        :stripe='stripe'
                        :options='options'
                        @change='expiry = $event.complete'
                        ></card-expiry>`

Options is declared as a prop
`options: {
            type: Object,
            default: function() { return {}}
        },'

I'm not sure why it's throwing this error on certain Safari users, any idea?

**Comment by techn0guy** [comment]
After updating my Mac to the latest OS I am experiencing this issue with the desktop version of Safari as well.

I'm experiencing this issue with vue 2.5.16:
`TypeError: undefined is not an object (evaluating 'e.$options')`

And this error if I update to vue 2.6.1:
`Error in nextTick: "TypeError: undefined is not an object (evaluating 'vm.$scopedSlots')"`

**Comment by corydemille** [comment]
I am getting this error now too. Any insights?

**Comment by pierremanceaux** [comment]
+1, same error here. I have been looking into this error for quite some time, but no solution so far... Anyone else?

**Comment by andreaslillebo** [comment]
I just submitted a pull request that fixes this problem.

It seems to only affect iOS >= 12.2 & macOS >= 10.14.4.

**Comment by thienhophu** [comment]
It happens when Stripe tries to create before it is mounted. Put Stripe in `mounted() `will solve the problems.

**Comment by kyoukhana** [comment]
Has this issue been resolved yet?

**Comment by thienhophu** [comment]
Still work for me. @kyoukhana

**Comment by reado** [comment]
@thienhophu could you explain what you mean by putting stripe in `mounted()`

Thanks

**Comment by thienhophu** [comment]
@reado As I tracked back then, stripe try to initialize right away without waiting for the page is fully loaded. Therefore, put Stripe initial in the `mounted()` will hold it back until the page is loaded.

**Comment by softbeehive** [comment]
Hey people, it shouldn't be an issue in `v1.0.0` because `StripeElement` component in the scoped slot mounts only after stripe instance object and stripe part of elements created. Just make sure you follow the structure:
```html
<StripeElements ... >
  <StripeElement ... />
</StripeElements>
```
