### ISSUE TITLE
Multiple Elements Example Not Working

### ISSUE THREAD

**Issue by purplelady105** [ectoflow/vue-stripe-elements#72]
I followed the example in your docs at: https://www.npmjs.com/package/vue-stripe-elements-plus#multiple-elements but I do not see the components rendering on my screen. I threw some CSS in so you could see where the elements are supposed to be.

This is what I see:
![image](https://user-images.githubusercontent.com/28715727/58054995-3aa40900-7b11-11e9-8c6a-70b02466c861.png)

Here is the Vue component in the HTML:
![image](https://user-images.githubusercontent.com/28715727/58054898-f31d7d00-7b10-11e9-9ce6-651869143fdb.png)

Here is where I import and define the components:
![image](https://user-images.githubusercontent.com/28715727/58054940-19dbb380-7b11-11e9-9ba9-9699ec296b97.png)

No errors in the console - only a couple of warnings:
![image](https://user-images.githubusercontent.com/28715727/58055106-8a82d000-7b11-11e9-9e2e-cb05cd4adc66.png)

What am I missing here?

**Comment by softbeehive** [comment]
Hi @purplelady105, in v1.0.0 multiple elements is no longer the issue.
