### ISSUE TITLE
Force locale

### ISSUE THREAD

**Issue by cgrisar** [ectoflow/vue-stripe-elements#79]
Hi,

does anyone know how to force a locale?

the documentation says stripe('pk_xxxx', options) but using

'''<card stripe="['pk_xxxx', {locale:'nl'}]"</card>''' doesn't help

**Comment by sedrickcz** [comment]
You can put to `stripe` prop String or Instance. So you can do something like this:

```
<card
   class="stripe-card"
  :class="{ complete }"
  :stripe="stripeInstance"
  :options="stripeOptions"
  @change="complete = $event.complete"
/>

...

data() {
  return {
    stripeInstance: Stripe('pk_test_6pRNASCoBOK....', { locale: 'nl' }),
    complete: false,
    ...
  };
},
....
```

**Comment by softbeehive** [comment]
Closing, seems like @sedrickcz answered the question
