### ISSUE TITLE
Strong Customer Authentication and Additional Info

### ISSUE THREAD

**Issue by OneMoreRound82** [ectoflow/vue-stripe-elements#83]
Does this adhere to the new SCA rule that is in effect of Septemeber 2019?
Is there a way to attach other details sent with the token such as name, address, receipt email?

**Comment by Skasi** [comment]
Yes, provided your backend/frontend supports it, and yes, check out the [Stripe docs for `createToken`](https://stripe.com/docs/stripe-js/reference#stripe-create-token) as linked in [this project's Readme](https://github.com/fromAtoB/vue-stripe-elements#supported-stripe-elements-functions).

**Comment by dvlden** [comment]
Yes, although I think that you should replace `createToken()` use, with `handleCardSetup()`.
Also, if in the past your FE application did register and charge in the same step, at this point, it must be separated.

1. Register your customer (and BE should provide you back with `clientSecret`
2. Let the customer enter card details... On submit, call `handleCardSetup`...

This is my understanding. Correct me if I'm wrong? Can we still register and charge in a single step?

**Comment by softbeehive** [comment]
Hey folks, closing this. `confirmCardSetup` is available in v1.0.0
