### ISSUE TITLE
How do we use createPaymentMethod() with this?

### ISSUE THREAD

**Issue by bkuhl** [ectoflow/vue-stripe-elements#91]
It'd be very helpful if the README could be updated to work with the new `createPaymentMethod()` approach since that's the new recommended way to create payment methods.  Right now it doesn't seem to work.  The underlying issue I'm trying to figure out is how to obtain the credit card info from the underlying `Card` vue component.  `createPaymentMethod()` wants to be passed an object that contains the credit card info, see https://stripe.com/docs/api/payment_methods/create#create_payment_method-card

It doesn't look as though it's possible to obtain the `Card` component's credit card info to pass to this method.

I'm updating `createToken()` to use `createPaymentMethod()` and am seeing the error `Invalid value for createPaymentMethod: value should be object. You specified: undefined`

**Comment by bkuhl** [comment]
The underlying issue I'm trying to figure out is how to obtain the credit card info from the underlying `Card` vue component.  `createPaymentMethod()` wants to be passed an object that contains the credit card info, see https://stripe.com/docs/api/payment_methods/create#create_payment_method-card

**Comment by seergiue** [comment]
Same issue here. I'd like to know how to work with createPaymentMethod with this library.

**Comment by seergiue** [comment]
I managed to use the core library of stripe to achieve the same without using this library:

`
<template>
    <div>
        <div id="card-element">
            
        </div>
        <button @click="pay">Save card</button>
    </div>
</template>

<script>
    export default {
        data() {
            return {
                stripe: null,
                card: null
            }
        },
        methods: {
            pay() {
                let that = this
                this.stripe.createPaymentMethod({
                    type: 'card',
                    card: that.card
                })
                    .then((d) => {
                        console.log(d)
                    })
                    .catch((e) => {
                        console.log(e)
                    })
            }
        },
        mounted() {
            this.stripe = Stripe('pk_test_XXXX')
            this.card = this.stripe.elements().create('card')
            this.card.mount('#card-element')
        }
    }
</script>
`

**Comment by bkuhl** [comment]
I ended up abandoning this library due to lack of examples and usages.  I ended up using your example, and https://github.com/stripe/stripe-billing-typographic/blob/master/client/src/components/Payment.vue as a good point of reference and things are progressing well.  Thanks for sharing!

**Comment by BaiMaoLi** [comment]
I don't think this library is perfect.
Have lacks of examples, lacks of community.
It takes out the time of developers.

**Comment by BenElgar** [comment]
For anyone else encountering this, it's necessary to specify the createPaymentMethod card type and options. In other words, the following should work:
```
createPaymentMethod('card', {})
```

**Comment by James-Don** [comment]
> For anyone else encountering this, it's necessary to specify the createPaymentMethod card type and options. In other words, the following should work:
> 
> ```
> createPaymentMethod('card', {})
> ```

Yes  BenElgar you can if you read their code:
Stripe.createPaymentMethod = (cardType, data) => Stripe.instance.createPaymentMethod(cardType, element, data)

**Comment by sjelfull** [comment]
@BenElgar Thanks, that worked

**Comment by softbeehive** [comment]
In v1.0.0 you can access any instance method via `StripeElement` Vue component instance
See example: https://github.com/ectoflow/vue-stripe-elements#3-use-built-in-components

```js
methods: {
  pay () {
    // ref in template
    const groupComponent = this.$refs.elms
    groupComponent.instance.createPaymentMethod()
  }
}
```
