### ISSUE TITLE
stripe.handleCardSetup(clientSecret,element,data?) is deprecated!!

### ISSUE THREAD

**Issue by muhghazaliakbar** [ectoflow/vue-stripe-elements#97]
Regarding to: https://stripe.com/docs/js/deprecated/handle_card_setup_element the `handleCardSetup` is deprecated and replaced with: https://stripe.com/docs/js/setup_intents/confirm_card_setup

anyone can help with that?

**Comment by zpoll92** [comment]
Please replace this, it's really confusing.

**Comment by softbeehive** [comment]
Fixed by #120
