### ISSUE TITLE
handleCardPayment is now called confirmCardPayment

### ISSUE THREAD

**Issue by quiquelhappy** [ectoflow/vue-stripe-elements#99]
https://stripe.com/docs/js/deprecated/handle_card_payment_element

**Comment by nj167252** [comment]
Is version 0.3.3 available? When I installed this package I got the 0.3.2 package. I see that in the fix (0.3.3) confirmCardPayment was added.

**Comment by jondashkyle** [comment]
Quick bump for release `0.3.3`!

**Comment by zpoll92** [comment]
Bump to release 0.3.3 ASAP!

**Comment by JeffJassky** [comment]
Bueler?

**Comment by kyosifov** [comment]
Is this project dead?

**Comment by quiquelhappy** [comment]
it seems

**Comment by softbeehive** [comment]
Hey folks, I get your pain. This package has been almost abandoned, but I revived it in v1.0.0.
You can use `confirmCardPayment` or any other stripe instance method via `StripeElements` vue component instance
Check the example in readme: [access instance methods](https://github.com/ectoflow/vue-stripe-elements#3-use-built-in-components)
